version: '3'

services:

  bot:
    build: ./bot
    environment:
      - PORT=3000
      - NODE_ENV=production
      - TELEGRAM_API_TOKEN=${TELEGRAM_API_TOKEN}
    container_name: telegram-bot-example
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "50"
    restart: always
